import {test,expect,type Page} from '@playwright/test';
const state=(page:Page)=>page.evaluate(()=>(window as any).__MIA_QA__?.snapshot());
async function point(page:Page,x:number,y:number){const b=await page.locator('canvas').boundingBox();if(!b)throw new Error('No canvas');return{x:b.x+x*b.width/1440,y:b.y+y*b.height/900};}
async function tap(page:Page,x:number,y:number){const p=await point(page,x,y);await page.touchscreen.tap(p.x,p.y);}
async function drag(page:Page,x:number,y:number,endX:number,endY:number){const a=await point(page,x,y),b=await point(page,endX,endY);await page.mouse.move(a.x,a.y);await page.mouse.down();await page.mouse.move(b.x,b.y,{steps:16});await page.waitForTimeout(100);await page.mouse.up();}
async function goto(page:Page,name:string,x:number){await tap(page,x,839);await expect.poll(async()=>(await state(page)).scene).toBe(name);await page.waitForTimeout(400);}
async function make(page:Page){let s=await state(page);if(!s.freezerOpen){await tap(page,157,425);await expect.poll(async()=>(await state(page)).freezerOpen).toBe(true);}await drag(page,s.order.vessel==='cup'?191:120,s.order.vessel==='cup'?508:419,900,430);await expect.poll(async()=>(await state(page)).vessel).toBe(s.order.vessel==='cup'?'cup':'cone');
 const flavour=s.order.flavour==='any'?'vanilla':s.order.flavour;const x={strawberry:458,vanilla:624,chocolate:790}[flavour as 'vanilla'];await drag(page,x,334,909,345);await expect.poll(async()=>(await state(page)).scoops.length).toBeGreaterThan(0);await drag(page,447,477,909,325);await expect.poll(async()=>(await state(page)).toppings.length).toBe(1);const before=(await state(page)).served;await drag(page,909,385,1260,570);await expect.poll(async()=>(await state(page)).served).toBe(before+1);}
test.beforeEach(async({page})=>{await page.goto('./?qa=1');await expect(page.locator('canvas')).toBeVisible();await expect(page.locator('#loading')).toHaveCount(0);await expect.poll(async()=>(await state(page))?.scene).not.toBe('Boot');await page.waitForTimeout(500);});
test('canvas loads, original assets load, and an ice cream is prepared and served',async({page})=>{const errors:string[]=[];page.on('pageerror',e=>errors.push(e.message));const initial=(await state(page)).coins;await make(page);expect((await state(page)).coins).toBe(initial+3);const broken=await page.evaluate(()=>performance.getEntriesByType('resource').filter((e:any)=>e.responseStatus>=400).map(e=>e.name));expect(broken).toEqual([]);expect(errors).toEqual([]);});
test('touch navigation, usable reward, drag placement and restart restore the world',async({page})=>{await goto(page,'Room',860);await tap(page,766,559);await expect.poll(async()=>(await state(page)).unlocked).toContain('plant');await drag(page,720,660,1000,682);await expect.poll(async()=>(await state(page)).placements.plant.x).toBeGreaterThan(900);const coins=(await state(page)).coins;await page.reload();await expect.poll(async()=>(await state(page))?.scene).toBe('Room');expect((await state(page)).coins).toBe(coins);expect((await state(page)).placements.plant.x).toBeGreaterThan(900);});
test('a real swipe launches the ball, scores, and awards a coin',async({page})=>{await goto(page,'Playground',720);const before=(await state(page)).coins;await drag(page,620,700,686,510);await expect.poll(async()=>(await state(page)).score).toBe(1);expect((await state(page)).coins).toBe(before+1);expect((await state(page)).goals).toBe(1);});
test('learning is occasional and berry manipulation records the correct independent skill',async({page})=>{await make(page);await page.waitForTimeout(3900);await make(page);await page.waitForTimeout(3900);expect((await state(page)).order.learning).toBe(true);await tap(page,1222,335);await expect.poll(async()=>(await state(page)).berry).not.toBe(null);let b=(await state(page)).berry;
 for(let step=0;step<b.challenge.steps.length;step++){b=(await state(page)).berry;const action=b.challenge.steps[step];for(let i=0;i<action.amount;i++){if(action.op==='+')await drag(page,270,407,830,470);else await drag(page,624,360,280,460);}await tap(page,1146,700);}
 b=(await state(page)).berry;if(b){expect(b.phase).toBe('count');for(let i=0;i<b.challenge.answer;i++)await tap(page,934,632);await tap(page,1146,700);}await expect.poll(async()=>(await state(page)).served).toBe(3);
 await tap(page,1370,65);await page.getByLabel('Grown-up code').fill('42');await page.getByRole('button',{name:'Continue',exact:true}).click();await expect(page.getByRole('heading',{name:"Mia's grown-up corner"})).toBeVisible();await expect(page.getByText('Version 5.0.0',{exact:false})).toBeVisible();});
test('parent toggles persist and portrait offers a safe orientation choice',async({page})=>{await tap(page,1370,65);await page.getByLabel('Grown-up code').fill('42');await page.getByRole('button',{name:'Continue',exact:true}).click();await page.getByLabel('Quiet background music').uncheck();await page.getByLabel('Only free play').check();await page.getByRole('button',{name:'Close parent settings'}).click();await page.reload();await page.waitForTimeout(600);await tap(page,1370,65);await page.getByLabel('Grown-up code').fill('42');await page.getByRole('button',{name:'Continue',exact:true}).click();await expect(page.getByLabel('Quiet background music')).not.toBeChecked();await expect(page.getByLabel('Only free play')).toBeChecked();await page.getByRole('button',{name:'Close parent settings'}).click();await page.setViewportSize({width:768,height:1024});await expect(page.getByText('Turn your iPad sideways.')).toBeVisible();await page.getByRole('button',{name:'Play this way'}).click();await expect(page.locator('#rotate')).toBeHidden();expect(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth)).toBe(true);});
test('service worker supports reload offline after its first installation',async({page,context})=>{await page.evaluate(async()=>{await navigator.serviceWorker.ready;});await expect.poll(()=>page.evaluate(()=>!!navigator.serviceWorker.controller)).toBe(true);await goto(page,'Playground',720);await context.setOffline(true);await page.reload();await expect(page.locator('canvas')).toBeVisible();await expect.poll(async()=>(await state(page))?.scene).toBe('Playground');await context.setOffline(false);});
