import Phaser from 'phaser';
export const W=1440,H=900;
export const INK=0x294e4c,CREAM=0xfff2d6,CORAL=0xe9846b,TEAL=0x69a999;
export const text=(scene:Phaser.Scene,x:number,y:number,value:string,size=24,color='#294e4c')=>scene.add.text(x,y,value,{fontFamily:'MiaRounded, Trebuchet MS, sans-serif',fontSize:`${size}px`,fontStyle:'bold',color,align:'center',lineSpacing:4}).setOrigin(.5);
export function plate(scene:Phaser.Scene,x:number,y:number,w:number,h:number,color=CREAM,r=24){const c=scene.add.container(x,y),g=scene.add.graphics();g.fillStyle(0x584c39,.18).fillRoundedRect(-w/2,-h/2+7,w,h,r);g.fillStyle(color).fillRoundedRect(-w/2,-h/2,w,h,r);g.lineStyle(2,0x6c7256,.3).strokeRoundedRect(-w/2,-h/2,w,h,r);c.add(g);return c;}
export function button(scene:Phaser.Scene,x:number,y:number,w:number,label:string,action:()=>void,color=CREAM,icon?:string){const c=plate(scene,x,y,w,64,color,24);if(icon)c.add(scene.add.image(label?-w/2+35:0,0,icon).setDisplaySize(42,42));if(label)c.add(text(scene,icon?13:0,0,label,22));c.setSize(w,64).setInteractive({useHandCursor:true});c.on('pointerdown',()=>{scene.tweens.add({targets:c,scaleX:.96,scaleY:.94,duration:70});});c.on('pointerup',()=>{scene.tweens.add({targets:c,scale:1,duration:220,ease:'Back.Out'});action();});c.on('pointerout',()=>scene.tweens.add({targets:c,scale:1,duration:140}));return c;}
export function burst(scene:Phaser.Scene,x:number,y:number,count=12){for(let i=0;i<count;i++){const p=scene.add.image(x,y,'spark').setDisplaySize(12+Math.random()*16,12+Math.random()*16).setDepth(1800);const a=Math.random()*Math.PI*2,r=50+Math.random()*85;scene.tweens.add({targets:p,x:x+Math.cos(a)*r,y:y+Math.sin(a)*r-25,alpha:0,angle:160,scale:0,duration:600+Math.random()*300,ease:'Quad.Out',onComplete:()=>p.destroy()});}}
export function pop(scene:Phaser.Scene,obj:any){const sx=obj.scaleX,sy=obj.scaleY;scene.tweens.add({targets:obj,scaleX:sx*1.12,scaleY:sy*.92,yoyo:true,duration:130,ease:'Sine.InOut'});}
export function tag(scene:Phaser.Scene,x:number,y:number,label:string,w=150){const c=plate(scene,x,y,w,40,0xffe9bd,12);c.add(text(scene,0,0,label,18));return c;}
