import Phaser from 'phaser';
import { save,audio } from '../services';
import { skillLabels,topicKeys } from '../../learning/config';
import { SKILLS, type Stage } from '../../learning/types';
import { VERSION } from '../../persistence/SaveStore';
export function openParent(scene:Phaser.Scene){
 const root=document.getElementById('parent-root')!;if(root.children.length)return;
 scene.scene.pause();const wrap=document.createElement('div');wrap.className='parent-backdrop';root.append(wrap);
 const close=()=>{wrap.remove();audio.settings(save.data.preferences.sound,save.data.preferences.music);scene.scene.resume();scene.events.emit('settings-changed');};
 wrap.innerHTML='<section class="parent-panel parent-gate" role="dialog" aria-modal="true" aria-labelledby="gate-title"><h1 id="gate-title">Grown-ups only</h1><p>Enter the number <strong>forty-two</strong>.</p><label for="parent-code">Grown-up code</label><input id="parent-code" inputmode="numeric" maxlength="2" autocomplete="off"/><div><button id="gate-cancel">Back to play</button><button id="gate-open">Continue</button></div></section>';
 wrap.querySelector('#gate-cancel')!.addEventListener('click',close);
 wrap.querySelector('#gate-open')!.addEventListener('click',()=>{if((wrap.querySelector('#parent-code')as HTMLInputElement).value==='42')render();else (wrap.querySelector('#parent-code')as HTMLInputElement).value='';});
 const render=()=>{
  const data=save.data;
  wrap.innerHTML=`<section class="parent-panel" role="dialog" aria-modal="true" aria-labelledby="parent-title"><div class="parent-header"><div><h1 id="parent-title">Mia's grown-up corner</h1><p class="muted">A little learning. Lots of room to play.</p></div><button class="close" aria-label="Close parent settings">×</button></div><div class="setting"><label for="sound">Sound effects</label><input id="sound" type="checkbox" ${data.preferences.sound?'checked':''}/></div><div class="setting"><label for="music">Quiet background music</label><input id="music" type="checkbox" ${data.preferences.music?'checked':''}/></div><div class="setting"><label for="freePlay">Only free play (no learning requests)</label><input id="freePlay" type="checkbox" ${data.preferences.freePlay?'checked':''}/></div><div class="setting"><label for="adaptive">Adapt each skill to confidence</label><input id="adaptive" type="checkbox" ${data.preferences.adaptive?'checked':''}/></div><div class="setting"><label for="stage">Learning focus</label><select id="stage"><option value="auto">Follow confidence</option><option value="A">Two-digit ± one-digit</option><option value="B">Crossing ten</option><option value="C">Mixed two-step changes</option></select></div><h2>Current school topics</h2><div class="topics">${SKILLS.map(s=>`<div class="setting"><label for="topic-${s}">${skillLabels[s]}</label><input id="topic-${s}" type="checkbox" ${data.topics.math[topicKeys[s]]?'checked':''}/></div>`).join('')}</div><p class="muted">German, English and other maths packs have configuration slots; their activities are not included in this release.</p><h2>Learning by skill</h2><table><thead><tr><th>Skill</th><th>Completed</th><th>First try, unaided</th><th>Retries / hints</th></tr></thead><tbody>${SKILLS.map(s=>{const p=data.skills[s];return`<tr><td>${skillLabels[s]}</td><td>${p?.attempts||0}</td><td>${p?.attempts?Math.round(p.firstTry/p.attempts*100)+'%':'—'}</td><td>${p?.retries||0} / ${p?.hints||0}</td></tr>`;}).join('')}</tbody></table><p class="muted">Accuracy includes completed berry activities. Counting visible objects is allowed. Time is recorded only for context; speed never raises difficulty.</p><h2>Your world</h2><p>${data.served} customers served · ${data.goals} baskets · ${data.unlocked.length} collected items</p><p>Progress stays on this browser and device. No accounts, ads or tracking. Clearing browser data removes it.</p><button id="reset-request" class="danger">Reset this world…</button><div id="reset-confirm"></div><p class="version muted">Version ${VERSION} · save format ${data.schema}${data.legacyImported?' · prototype coins imported':''}</p></section>`;
  wrap.querySelector('.close')!.addEventListener('click',close);
  (wrap.querySelector('#stage') as HTMLSelectElement).value=data.preferences.stage;
  for(const key of ['sound','music','adaptive','freePlay'] as const)wrap.querySelector('#'+key)!.addEventListener('change',event=>{data.preferences[key]=(event.target as HTMLInputElement).checked;save.commit();audio.settings(data.preferences.sound,data.preferences.music);});
  wrap.querySelector('#stage')!.addEventListener('change',event=>{data.preferences.stage=(event.target as HTMLSelectElement).value as Stage;save.commit();});
  for(const skill of SKILLS)wrap.querySelector('#topic-'+skill)!.addEventListener('change',event=>{data.topics.math[topicKeys[skill]]=(event.target as HTMLInputElement).checked;save.commit();});
  wrap.querySelector('#reset-request')!.addEventListener('click',()=>{const box=wrap.querySelector('#reset-confirm')!;box.innerHTML='<div class="reset-box"><strong>Erase coins, decorations and learning history on this device?</strong><div><button id="cancel-reset">Keep my world</button><button id="confirm-reset" class="danger">Erase and start fresh</button></div></div>';box.querySelector('#cancel-reset')!.addEventListener('click',()=>box.innerHTML='');box.querySelector('#confirm-reset')!.addEventListener('click',async()=>{await save.reset();wrap.remove();scene.scene.resume();scene.scene.start('Shop');});});
 };
}
