import Phaser from 'phaser';
import { WorldScene } from './WorldScene';
import { Actor } from '../entities/Actor';
import { audio,learning,save } from '../services';
import { button,plate,text,burst,tag,pop } from '../ui/paint';
import { BerryActivity } from '../systems/BerryActivity';
export class ShopScene extends WorldScene {
 private customer?:Actor;private orderBubble?:Phaser.GameObjects.Container;private freezerOpen=false;private door!:Phaser.GameObjects.Image;private storage:Phaser.GameObjects.Image[]=[];private dish?:Phaser.GameObjects.Container;private serving=false;private vessel='cone';private scoops:string[]=[];private toppings:string[]=[];private order={flavour:'strawberry',vessel:'any',learning:false};private berry?:BerryActivity;private register!:Phaser.GameObjects.Image;private decoration=0;
 constructor(){super('Shop');}
 create(){this.setup('Shop','Scoop & Smile','Open the freezer. Make something delicious!');this.freezerOpen=false;this.storage=[];this.scoops=[];this.toppings=[];this.dish=undefined;this.berry=undefined;this.serving=false;
  const brand=plate(this,749,224,295,83,0xffe6ae,40);brand.add(text(this,0,-13,'SCOOP & SMILE',24));brand.add(text(this,0,17,'made with a little magic',15,'#977358'));
  this.add.image(159,451,'freezer').setDisplaySize(220,290).setDepth(11);
  const cone=this.add.image(120,419,'cone').setDisplaySize(54,81).setDepth(12);const cup=this.add.image(191,508,'cup').setDisplaySize(60,57).setDepth(12);this.storage.push(cone,cup);
  for(const [obj,type]of [[cone,'cone'],[cup,'cup']] as const){this.interactions.draggable(obj,`vessel:${type}`,{source:true,tap:()=>this.startDish(type)});obj.setVisible(false);}
  this.door=this.add.image(57,310,'freezer-door').setOrigin(0,0).setDisplaySize(208,252).setDepth(14).setInteractive({useHandCursor:true});this.door.on('pointerup',()=>this.toggleFreezer());
  tag(this,160,608,'OPEN ME',125).setDepth(18);
  const openHand=this.add.image(228,512,'hand').setDisplaySize(43,43).setDepth(15);this.tweens.add({targets:openHand,x:217,duration:750,repeat:-1,yoyo:true});this.door.once('pointerup',()=>openHand.destroy());
  const flavours=['strawberry','vanilla','chocolate'];if(save.data.unlocked.includes('mint'))flavours.push('mint');
  flavours.forEach((flavour,i)=>{const x=flavours.length===4?442+i*132:458+i*166;this.add.image(x,354,`tub-${flavour}`).setDisplaySize(144,89).setDepth(16);const scoop=this.add.image(x,334,`scoop-${flavour}`).setDisplaySize(82,71).setDepth(17);scoop.setSize(115,95);this.interactions.draggable(scoop,`scoop:${flavour}`,{source:true,tap:()=>this.addScoop(flavour)});tag(this,x,404,flavour[0].toUpperCase()+flavour.slice(1),136).setDepth(18);});
  [['berry',447],['sprinkles',544],['wafer',639],['cherry',735]].forEach(([key,x])=>{const item=this.add.image(x as number,477,key as string).setDisplaySize(key==='wafer'?30:52,key==='berry'?57:77).setDepth(20);this.interactions.draggable(item,`topping:${key}`,{source:true,tap:()=>this.addTopping(key as string)});});
  this.register=this.add.image(1100,446,'register').setDisplaySize(137,130).setDepth(20).setInteractive({useHandCursor:true});this.register.on('pointerup',()=>{pop(this,this.register);audio.play('coin');const drawer=plate(this,1100,498,114,36,0x628f7e,8).setDepth(26);for(let i=0;i<3;i++)drawer.add(this.add.image(-30+i*30,0,'coin').setDisplaySize(25,25));this.tweens.add({targets:drawer,y:518,duration:250,yoyo:true,hold:650,onComplete:()=>drawer.destroy()});});
  const guide=this.add.graphics().setDepth(18);guide.lineStyle(3,0xfff4d9,.8).strokeEllipse(909,478,158,32);
  this.interactions.zone({id:'make-icecream',bounds:()=>new Phaser.Geom.Rectangle(792,258,217,286),accepts:k=>k.startsWith('vessel:')||k.startsWith('scoop:')||k.startsWith('topping:'),drop:(_obj,kind)=>{const [type,key]=kind.split(':');if(type==='vessel')this.startDish(key);else if(type==='scoop')this.addScoop(key);else this.addTopping(key);return true;}});
  this.interactions.zone({id:'serve-customer',bounds:()=>new Phaser.Geom.Rectangle(1145,320,285,404),accepts:k=>k==='dish',drop:()=>this.serve()});
  button(this,972,601,151,'Fresh cone',()=>{this.dish?.destroy();this.dish=undefined;this.scoops=[];this.toppings=[];this.say('Cone or cup? Pick one from the freezer.');},0xf2c6a2).setDepth(60);
  const bell=this.add.image(1074,595,'bell').setDisplaySize(68,68).setDepth(62).setInteractive({useHandCursor:true});bell.on('pointerup',()=>{audio.play('bell');pop(this,bell);this.customer?.wave();burst(this,1074,558,4);});
  const counterSign=plate(this,686,589,292,67,0xe9c899,16).setDepth(55);counterSign.add(text(this,0,-9,'a scoop of happiness',21,'#796547'));counterSign.add(text(this,0,16,'tap the sign to decorate',13,'#796547'));counterSign.setSize(292,67).setInteractive({useHandCursor:true});const paintBunting=()=>{const colors=[0xe48b72,0x87baa2,0xe6c379,0xb4a6c3];const bunting=this.add.graphics().setDepth(56);bunting.lineStyle(3,0x8f7953).beginPath().moveTo(320,510).lineTo(1140,510).strokePath();for(let i=0;i<10;i++){bunting.fillStyle(colors[(i+save.data.shopStyle)%4]).fillTriangle(332+i*80,510,383+i*80,510,358+i*80,550);}return bunting;};let flags:Phaser.GameObjects.Graphics|undefined=save.data.shopStyle?paintBunting():undefined;counterSign.on('pointerup',()=>{save.data.shopStyle=save.data.shopStyle%4+1;save.commit();flags?.destroy();flags=paintBunting();audio.play('place');});
  const windowHit=this.add.zone(207,229,220,220).setInteractive();windowHit.on('pointerup',()=>{audio.play('bird');const f=this.add.image(167,237,'flower').setDisplaySize(25,25);this.tweens.add({targets:f,x:307,y:133,angle:270,alpha:0,duration:1500,onComplete:()=>f.destroy()});});
  this.addDecor('Shop');this.arrive();
  this.events.once('shutdown',()=>this.berry?.destroy());
 }
 private toggleFreezer(){this.freezerOpen=!this.freezerOpen;audio.play('open');this.tweens.add({targets:this.door,scaleX:this.freezerOpen?.12:1,duration:350,ease:'Cubic.InOut'});this.storage.forEach(o=>{o.setVisible(this.freezerOpen);if(o.input)o.input.enabled=this.freezerOpen;});}
 startDish(type:string){if(this.serving)return;this.dish?.destroy();this.scoops=[];this.toppings=[];this.vessel=type;this.dish=this.add.container(909,478).setDepth(30);this.dish.add(this.add.image(0,type==='cone'?-58:-40,type).setDisplaySize(type==='cone'?83:106,type==='cone'?124:101));this.dish.setSize(165,256).setInteractive(new Phaser.Geom.Rectangle(-1.5,-107,168,250),Phaser.Geom.Rectangle.Contains);this.interactions.draggable(this.dish,'dish');this.say('Drag a flavour onto your '+type+'.');audio.play('place');burst(this,909,400,4);}
 addScoop(flavour:string){if(this.serving)return;if(!this.dish){this.say('Choose a cone or cup first.');return;}if(this.scoops.length>=3){this.say('A lovely tall ice cream! Time for toppings.');return;}
  const index=this.scoops.length;this.scoops.push(flavour);const image=this.add.image((index%2===0?1:-1)*index*4,(this.vessel==='cone'?-135:-85)-index*51,`scoop-${flavour}`).setDisplaySize(111,97);this.dish.add(image);const target=image.y;image.y-=45;image.setAlpha(.2);this.tweens.add({targets:image,y:target,alpha:1,duration:320,ease:'Bounce.Out'});audio.play('place');if(index===0)this.say('Add a topping, or drag it to your friend.');}
 addTopping(key:string){if(!this.dish||!this.scoops.length){this.say('A scoop first, then the finishing touches.');return;}if(this.toppings.length>=5){this.say('Ready to share!');return;}const index=this.toppings.length;this.toppings.push(key);const top=(this.vessel==='cone'?-148:-100)-(this.scoops.length-1)*51;const image=this.add.image(-32+(index%4)*21,top-22,key).setDisplaySize(key==='wafer'?20:28,key==='wafer'?94:30);if(key==='sprinkles'){image.setTexture('spark').setTint(0xe67f9b);image.setDisplaySize(22,22);for(let i=0;i<9;i++){const s=this.add.rectangle(-35+Math.random()*70,top+Math.random()*30,8,3,[0xe6798a,0xefd376,0x6eafa2][i%3]).setAngle(Math.random()*180);this.dish.add(s);}}this.dish.add(image);audio.play('place');pop(this,image);}
 private arrive(){this.customer?.destroy();this.orderBubble?.destroy();this.serving=false;const count=save.data.served;const challengeAvailable=!save.data.preferences.freePlay&&!!learning().request('quantity_change');this.order={flavour:count===0?'strawberry':Phaser.Utils.Array.GetRandom(['strawberry','vanilla','chocolate','any']),vessel:count%4===3?'cup':'any',learning:count%3===2&&challengeAvailable};
  this.customer=new Actor(this,1520,700,1+((count+save.data.visits)%3));this.customer.setScale(.89).setDepth(85);this.actors.push(this.customer);this.customer.walkTo(1274,700);
  this.orderBubble=plate(this,1222,266,326,218,0xfff6de,38).setDepth(90);
  const caption=this.order.learning?'Berry picnic?':this.order.vessel==='cup'?'A cup, please!':this.order.flavour==='any'?'Surprise me!':`${this.order.flavour[0].toUpperCase()+this.order.flavour.slice(1)}, please!`;
  this.orderBubble.add(text(this,0,-64,caption,23));
  this.orderBubble.add(this.add.image(0,7,this.order.learning?'berry':this.order.flavour==='any'?'scoop-vanilla':`scoop-${this.order.flavour}`).setDisplaySize(79,77));
  if(this.order.learning){const help=button(this,1222,335,189,"Let's help",()=>this.startBerries(),0xb5d2b3);help.setDepth(100);this.orderBubble.add(this.add.text(-85,52,'',{}));this.orderBubble.once('destroy',()=>help.destroy());}
  else this.orderBubble.add(text(this,0,77,this.order.vessel==='cup'?'in a little cup':'make it your way',17,'#8c7956'));
  const later=button(this,1298,731,149,'Bye for now',()=>{if(!this.serving){this.order.learning=false;this.order.flavour='any';this.order.vessel='any';this.orderBubble?.destroy();this.orderBubble=plate(this,1222,266,290,153,0xfff6de,36).setDepth(90);this.orderBubble.add(text(this,0,0,'Just a surprise scoop!',22));this.say('Keep playing. Any flavour is lovely.');}},0xffe3bc);later.setDepth(90);this.customer.once('destroy',()=>later.destroy());
 }
 private startBerries(){if(this.berry)return;const challenge=learning().request('quantity_change');if(!challenge)return;this.bubble?.destroy();this.berry=new BerryActivity(this,challenge,(completed)=>{this.berry=undefined;if(completed){this.reward('learning',1220,590);this.say('Picnic packed! Thank you.');this.depart();}else this.say('The picnic can wait. Keep playing.');});}
 private serve(){if(this.serving||!this.dish||!this.scoops.length)return false;if(this.order.learning){this.say('Tap “Let’s help” for the berry picnic.');return false;}if(this.order.flavour!=='any'&&!this.scoops.includes(this.order.flavour)){this.say(`Try a ${this.order.flavour} scoop for this friend.`);this.customer?.wave();audio.play('retry');return false;}if(this.order.vessel!=='any'&&this.vessel!==this.order.vessel){this.say('This friend would love a cup.');return false;}
  this.serving=true;const dish=this.dish;this.dish=undefined;dish.disableInteractive();this.reward('serve',1243,520);this.tweens.add({targets:dish,x:1240,y:590,scale:.6,alpha:0,duration:650,onComplete:()=>dish.destroy()});this.customer?.celebrate();this.say('Yum! More coins for your little world.');this.depart();return true;}
 private depart(){this.serving=true;this.orderBubble?.destroy();this.time.delayedCall(900,()=>this.customer?.walkTo(1510,700));this.time.delayedCall(3400,()=>this.arrive());}
 protected onSettings(){if(!this.berry)this.arrive();}
 snapshot(){return{...super.snapshot(),freezerOpen:this.freezerOpen,vessel:this.vessel,scoops:[...this.scoops],toppings:[...this.toppings],order:this.order,berry:this.berry?.snapshot()||null};}
}
